// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GoAway.proto

package com.eg.gofacade.dto;

public interface AskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.eg.gofacade.dto.AskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cid = 1;</code>
   * @return The cid.
   */
  java.lang.String getCid();
  /**
   * <code>string cid = 1;</code>
   * @return The bytes for cid.
   */
  com.google.protobuf.ByteString
      getCidBytes();

  /**
   * <code>string host = 2;</code>
   * @return The host.
   */
  java.lang.String getHost();
  /**
   * <code>string host = 2;</code>
   * @return The bytes for host.
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>int32 port = 3;</code>
   * @return The port.
   */
  int getPort();
}
