// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GoAway.proto

package com.eg.gofacade.dto;

public interface ByeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.eg.gofacade.dto.ByeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cid = 1;</code>
   * @return The cid.
   */
  java.lang.String getCid();
  /**
   * <code>string cid = 1;</code>
   * @return The bytes for cid.
   */
  com.google.protobuf.ByteString
      getCidBytes();
}
