// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GoAway.proto

package com.eg.gofacade.dto;

/**
 * Protobuf enum {@code com.eg.gofacade.dto.GoStatus}
 */
public enum GoStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ST_START = 0;</code>
   */
  ST_START(0),
  /**
   * <code>ST_OK = 200;</code>
   */
  ST_OK(200),
  /**
   * <code>ST_BAD = 400;</code>
   */
  ST_BAD(400),
  /**
   * <code>ST_GONE = 410;</code>
   */
  ST_GONE(410),
  /**
   * <code>ST_INNER_ERR = 500;</code>
   */
  ST_INNER_ERR(500),
  /**
   * <code>ST_BAD_G = 502;</code>
   */
  ST_BAD_G(502),
  /**
   * <code>ST_SRV_UA = 503;</code>
   */
  ST_SRV_UA(503),
  /**
   * <code>ST_GW_TO = 504;</code>
   */
  ST_GW_TO(504),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ST_START = 0;</code>
   */
  public static final int ST_START_VALUE = 0;
  /**
   * <code>ST_OK = 200;</code>
   */
  public static final int ST_OK_VALUE = 200;
  /**
   * <code>ST_BAD = 400;</code>
   */
  public static final int ST_BAD_VALUE = 400;
  /**
   * <code>ST_GONE = 410;</code>
   */
  public static final int ST_GONE_VALUE = 410;
  /**
   * <code>ST_INNER_ERR = 500;</code>
   */
  public static final int ST_INNER_ERR_VALUE = 500;
  /**
   * <code>ST_BAD_G = 502;</code>
   */
  public static final int ST_BAD_G_VALUE = 502;
  /**
   * <code>ST_SRV_UA = 503;</code>
   */
  public static final int ST_SRV_UA_VALUE = 503;
  /**
   * <code>ST_GW_TO = 504;</code>
   */
  public static final int ST_GW_TO_VALUE = 504;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static GoStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static GoStatus forNumber(int value) {
    switch (value) {
      case 0: return ST_START;
      case 200: return ST_OK;
      case 400: return ST_BAD;
      case 410: return ST_GONE;
      case 500: return ST_INNER_ERR;
      case 502: return ST_BAD_G;
      case 503: return ST_SRV_UA;
      case 504: return ST_GW_TO;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GoStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      GoStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GoStatus>() {
          public GoStatus findValueByNumber(int number) {
            return GoStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.eg.gofacade.dto.GoAway.getDescriptor().getEnumTypes().get(0);
  }

  private static final GoStatus[] VALUES = values();

  public static GoStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private GoStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.eg.gofacade.dto.GoStatus)
}

