// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GoAway.proto

package com.eg.gofacade.dto;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.eg.gofacade.dto.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cid = 1;</code>
   * @return The cid.
   */
  java.lang.String getCid();
  /**
   * <code>string cid = 1;</code>
   * @return The bytes for cid.
   */
  com.google.protobuf.ByteString
      getCidBytes();

  /**
   * <code>string word = 2;</code>
   * @return The word.
   */
  java.lang.String getWord();
  /**
   * <code>string word = 2;</code>
   * @return The bytes for word.
   */
  com.google.protobuf.ByteString
      getWordBytes();
}
