// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GoAway.proto

package com.eg.gofacade.dto;

public interface TalkRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.eg.gofacade.dto.TalkRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cid = 1;</code>
   * @return The cid.
   */
  java.lang.String getCid();
  /**
   * <code>string cid = 1;</code>
   * @return The bytes for cid.
   */
  com.google.protobuf.ByteString
      getCidBytes();

  /**
   * <code>int32 seq = 2;</code>
   * @return The seq.
   */
  int getSeq();

  /**
   * <code>bytes data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
